title: His Eminence's Website
remote_theme: daattali/beautiful-jekyll

plugins:
  - jekyll-remote-theme

markdown: GFM

navbar-links:
  Home: "/"
  Posts: "/posts/"
  Projects: "/proj/projects"
  About: "/about/"